-- ============================================================
-- SoloForte — Supabase Schema: drawings (LEGADO)
-- ============================================================
-- CANÔNICO: supabase/migrations/20260825050000_drawings_remote_sync.sql
-- ADR-021/027 · drawing sync via DrawingRemoteStore
--
-- Não editar este arquivo. Aplicar schema via migrations versionadas.
-- ============================================================
